### PR TITLE
Modified code that didn't work correctly after relocating aspectj

### PR DESCRIPTION
**Pull request by mduchrow**
Modified code that didn't work correctly after relocating aspectj to another base package.
This is in most cases about the hard-coded check of the package first character to 'o' which would fail if relocating aspectj to a package starting with a different character.

### CODE REVIEW

**Comment by mduchrow** [comment]
Created issue [https://bugs.eclipse.org/bugs/show_bug.cgi?id=536782](https://bugs.eclipse.org/bugs/show_bug.cgi?id=536782) for this pull request.

**Comment by aclement** [comment]
Thanks for the contribution!  I was looking to merge it - but I saw that 'ip-validation' error above. However, when I click on details I get a:
---
Current status
Validation status unavailable. Contact support.
---

Very helpful...  But I partly wonder if it is due to the git move that they have done at eclipse, I've had to update my git URLs for AspectJ because of the change.   Do you have any idea what the validation error is - can you access it?

**Comment by mduchrow** [comment]
After seeing this "check failed" I asked a guy who is committer for eclipse projects, what to do.
He told me that I must have an eclipse account and and sign the Eclipse Contributor Agreement (ECA).
Then the flag on the pull request will go away automatically after a few hours.
I did all this, but the pull request is still marked invalid.

**Comment by aclement** [comment]
Working this in as I build 1.9.2 - I've pulled your commit over and now I get this on attempting to push to the main repo:

```
remote: Reviewing commit: 7aa537bb
remote: Authored by: mduchrow <manfred.duchrow@caprica.de>
remote:
remote: The author is not a committer on the project.
remote: The author has a current Eclipse Contributor Agreement (ECA) on file.
remote: error: The author has not "signed-off" on the contribution.
remote: If there are multiple commits, please ensure that each commit is signed-off.
remote: Please see http://wiki.eclipse.org/ECA
```
Seems to be covered here: https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Signing_off_on_a_commit

Wonder if the lack of sign off is why it is still complaining in the ip-validation check.

**Comment by mduchrow** [comment]
Hi Andy,
thanks for the hint. I had no clue what was wrong.
It seems that signing off a commit afterwards is not possible.
So I think I have to do the changes once more on a current fork of aspectj and create a new signed-off commit and pull request.

**Comment by aclement** [comment]
Who knows why it is complaining now, I still can't access the reason... I have merged the changes (somehow) and you've signed the ECA, so I think we are good.

**Comment by mduchrow** [comment]
You finally got it in! Great!
Thank you very much for your endurance.

**Pull request closed without merging**
